version: '3.1'

services:
  backend:
    build: ./CateringApp
    command: bash run.sh
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql
    volumes:
        - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: cateringdb_new
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
