# Generated by Django 4.2.4 on 2023-08-08 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('price_per_day', models.FloatField(default=0.0)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date_from', models.DateField(auto_now=True)),
                ('order_date_to', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('total_price', models.FloatField(default=0.0)),
                ('diet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='catering.diet')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
