# Generated by Django 4.2.4 on 2023-09-22 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date_from',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_expired', models.DateTimeField()),
                ('code', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
